[package]
name = "droidid"
version = "0.1.0"
edition = "2024"


authors = ["Dr. Ippy <jdplumbingsoflo@gmail.com>"]
license = "MIT"
repository = "https://github.com/JDPlumbing/droidid"

[dependencies]
rand = "0.9.2"
